
theme: jekyll-theme-minimal
htmlwidgets: TRUE

# Name of website
title: Human-made Climate Change discussion on Reddit

# Your name to show in the footer
author: Albert K. Jacobsen, Aron D. Jacobsen, Phillip C. Højbjerg
